07BDCourseWork/07BDCourseWork/Controllers/BrigadeController.cs
using _07BDCourseWork.App_Start;
using _07BDCourseWork.Models;
using DAL.Interfaces;
using DAL.Repositories;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using _07BDCourseWork.Resources;

namespace _07BDCourseWork.Controllers
{
    public class BrigadeController : Controller
    {
        private readonly IUnitOfWork db = new EFUnitOfWork("name=DbModel");

        // GET: Brigade
        public ActionResult Index()
        {
            List<BrigadeDTO> model = new List<BrigadeDTO>();
            foreach (var item in db.Brigades.GetAll())
            {
                model.Add(item.ToBrigadeDTO());
            }
            return View("Index", model);
        }

        public ActionResult Sort(string sortOrder)
        {
            var model = CacheHelper.Get(CacheKeys.BrigadeModel) as List<BrigadeDTO>;
            model = model ?? db.Brigades.GetAll().Select(item => item.ToBrigadeDTO()).ToList();

            if (sortOrder == SortMethods.Name)
                return PartialView("_Table", model.OrderBy(x => x.Name).ToList());

            if (sortOrder == SortMethods.NameDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.Name).ToList());

            return PartialView("_table", model);
        }

        [HttpPost]
        public ActionResult Search(string name)
        {
            List<BrigadeDTO> model = db.Brigades.GetAll().Where(x => x.Name.StartsWith(name)).Select(item => item.ToBrigadeDTO()).ToList();
            return PartialView("_Table", model);
        }

        // GET: Brigade/Details/5
        public ActionResult Details(int id)
        {
            var model = db.Brigades.Get(id);

            if (model == null)
                return HttpNotFound();

            return View("Details", model.ToBrigadeDTO());
        }

        // GET: Brigade/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: Brigade/Create
        [HttpPost]
        public ActionResult Create(BrigadeDTO model, FormCollection collection)
        {
            ValidateUniqueName(model);

            if (ModelState.IsValid)
            {
                var modelDTO = model.ToBrigade();
                db.Brigades.Create(modelDTO);
                db.Save();
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        // GET: Brigade/Edit/5
        public ActionResult Edit(int id)
        {
            var model = db.Brigades.Get(id);

            if (model == null)
                return HttpNotFound();

            return View("Edit", model.ToBrigadeDTO());
        }

        // POST: Brigade/Edit/5
        [HttpPost]
        public ActionResult Edit(BrigadeDTO model, FormCollection collection)
        {
            var modelToUpdate = db.Brigades.Get(model.ID);

            if (modelToUpdate == null)
                return HttpNotFound();

            ValidateUniqueName(model);

            if (ModelState.IsValid)
            {
                modelToUpdate.Name = model.Name;
                db.Save();

                return RedirectToAction("Index");
            }

            return View("Edit", model);
        }

        // GET: Brigade/Delete/5
        public ActionResult Delete(int id)
        {
            var model = db.Brigades.Get(id);

            if (model == null)
                HttpNotFound();

            return View("Delete", model.ToBrigadeDTO());
        }

        // POST: Brigade/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var model = db.Brigades.Get(id);

            if (model == null)
                HttpNotFound();

            db.Brigades.Delete(id);
            db.Save();
            return RedirectToAction("Index");
        }

        private void ValidateUniqueName(BrigadeDTO model)
        {
            var existedSameName = db.Brigades.Find(x => x.Name == model.Name && x.ID != model.ID);

            if (existedSameName != null && existedSameName.Count() != 0)
            {
                ModelState.AddModelError("Name", Messages.BrigadeCreateValid_UniqName);
            }
        }
    }
}

07BDCourseWork/07BDCourseWork/Controllers/CarController.cs
using _07BDCourseWork.App_Start;
using _07BDCourseWork.Models;
using DAL.Repositories;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using _07BDCourseWork.Resources;

namespace _07BDCourseWork.Controllers
{
    public class CarController : Controller
    {
        private readonly EFUnitOfWork db = new EFUnitOfWork("name=DbModel");

        // GET: Car
        public ActionResult Index(string sortOrder)
        {
            List<CarDTO> model = db.Cars.GetAll().Select(item => item.ToCarDTO()).ToList();
            return View("Index", model);
        }

        public ActionResult Sort(string sortOrder)
        {
            var model = CacheHelper.Get(CacheKeys.CarModel) as List<CarDTO>;
            model = model ?? db.Cars.GetAll().Select(item => item.ToCarDTO()).ToList();

            if (sortOrder == SortMethods.IdCarcase)
                return PartialView("_Table", model.OrderBy(x => x.IdCarcase).ToList());
            if (sortOrder == SortMethods.IdCarcaseDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.IdCarcase).ToList());
            if (sortOrder == SortMethods.IdEngine)
                return PartialView("_Table", model.OrderBy(x => x.IdEngine).ToList());
            if (sortOrder == SortMethods.IdEngineDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.IdEngine).ToList());
            if (sortOrder == SortMethods.Owner)
                return PartialView("_Table", model.OrderBy(x => x.Owner).ToList());
            if (sortOrder == SortMethods.OwnerDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.Owner).ToList());
            if (sortOrder == SortMethods.FactoryNumber)
                return PartialView("_Table", model.OrderBy(x => x.FactoryNumber).ToList());
            if (sortOrder == SortMethods.FactoryNumberDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.FactoryNumber).ToList());

            return PartialView("_table", model);
        }

        [HttpPost]
        public ActionResult Filter(string carcase, string engine, string owner, string factory)
        {
            List<CarDTO> model = db.Cars.GetAll().Select(item => item.ToCarDTO()).ToList();

            model = model.Where(x => x.IdCarcase.ToString().StartsWith(carcase)).ToList();
            model = model.Where(x => x.IdEngine.ToString().StartsWith(engine)).ToList();
            model = model.Where(x => x.Owner.ToString().StartsWith(owner)).ToList();
            model = model.Where(x => x.FactoryNumber.ToString().StartsWith(factory)).ToList();

            return PartialView("_Table", model);
        }

        // GET: Car/Details/5
        public ActionResult Details(int id)
        {
            var model = db.Cars.Get(id);

            if (model == null)
                return HttpNotFound();

            return View("Details", model.ToCarDTO());
        }

        // GET: Car/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: Car/Create
        [HttpPost]
        public ActionResult Create(CarDTO model, FormCollection collection)
        {
            ValidateUniqueIdCarcase(model);
            ValidateUniqueFactoryNumber(model);
            ValidateUniqueIdEngine(model);

            if (ModelState.IsValid)
            {
                var modelDTO = model.ToCar();
                db.Cars.Create(modelDTO);
                db.Save();
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        // GET: Car/Edit/5
        public ActionResult Edit(int id)
        {
            var model = db.Cars.Get(id);

            if (model == null)
                return HttpNotFound();

            return View("Edit", model.ToCarDTO());
        }

        // POST: Car/Edit/5
        [HttpPost]
        public ActionResult Edit(CarDTO model, FormCollection collection)
        {
            var modelToUpdate = db.Cars.Get(model.ID);

            if (modelToUpdate == null)
                return HttpNotFound();

            ValidateUniqueIdCarcase(model);
            ValidateUniqueFactoryNumber(model);
            ValidateUniqueIdEngine(model);

            if (ModelState.IsValid)
            {
                modelToUpdate.IdCarcase = model.IdCarcase;
                modelToUpdate.IdEngine = model.IdEngine;
                modelToUpdate.Owner = model.Owner;
                modelToUpdate.FactoryNumber = model.FactoryNumber;
                db.Save();

                return RedirectToAction("Index");
            }

            return View("Edit", model);
        }

        // GET: Car/Delete/5
        public ActionResult Delete(int id)
        {
            var model = db.Cars.Get(id);

            if (model == null)
                HttpNotFound();

            return View("Delete", model.ToCarDTO());
        }

        // POST: Car/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var model = db.Cars.Get(id);

            if (model == null)
                HttpNotFound();

            //db.Cars.Delete(id);
            db.Context.Database.ExecuteSqlCommand($"DELETE FROM Car WHERE ID = {id}");
            db.Save();
            return RedirectToAction("Index");
        }

        private void ValidateUniqueIdCarcase(CarDTO model)
        {
            var existedSameName = db.Cars.Find(x => x.IdCarcase == model.IdCarcase && x.ID != model.ID);

            if (existedSameName != null && existedSameName.Count() != 0)
            {
                ModelState.AddModelError("IdCarcase", Messages.CarCreateValid_UniqNumber);
            }
        }

        private void ValidateUniqueIdEngine(CarDTO model)
        {
            var existedSameName = db.Cars.Find(x => x.IdEngine == model.IdEngine && x.ID != model.ID);

            if (existedSameName != null && existedSameName.Count() != 0)
            {
                ModelState.AddModelError("IdEngine", Messages.CarCreateValid_UniqNumber);
            }
        }

        private void ValidateUniqueFactoryNumber(CarDTO model)
        {
            var existedSameName = db.Cars.Find(x => x.FactoryNumber == model.FactoryNumber && x.ID != model.ID);

            if (existedSameName != null && existedSameName.Count() != 0)
            {
                ModelState.AddModelError("FactoryNumber", Messages.CarCreateValid_UniqNumber);
            }
        }
    }
}

07BDCourseWork/07BDCourseWork/Controllers/DefectController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DAL.Interfaces;
using DAL.Repositories;
using _07BDCourseWork.App_Start;
using _07BDCourseWork.Models;
using _07BDCourseWork.Resources;

namespace _07BDCourseWork.Controllers
{
    public class DefectController : Controller
    {
        private readonly IUnitOfWork db = new EFUnitOfWork("name=DbModel");

        // GET: Defect
        public ActionResult Index()
        {
            List<DefectDTO> model = db.Defects.GetAll().Select(item => item.ToDefectDTO()).ToList();

            if(model.Count != 0)
            {
                ViewBag.Min = (int)model.Min(x => x.Cost) - 1;
                ViewBag.Max = (int)model.Max(x => x.Cost) + 1;
            }

            return View("Index", model);
        }

        public ActionResult Sort(string sortOrder)
        {
            var model = CacheHelper.Get(CacheKeys.DefectModel) as List<DefectDTO>;
            model = model ?? db.Defects.GetAll().Select(item => item.ToDefectDTO()).ToList();

            if (sortOrder == SortMethods.Name)
                return PartialView("_Table", model.OrderBy(x => x.Name).ToList());
            if (sortOrder == SortMethods.NameDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.Name).ToList());
            if (sortOrder == SortMethods.Cost)
                return PartialView("_Table", model.OrderBy(x => x.Cost).ToList());
            if (sortOrder == SortMethods.CostDesc)
                return PartialView("_Table", model.OrderByDescending(x => x.Cost).ToList());

            return PartialView("_table", model);
        }

        [HttpPost]
        public ActionResult Filter(string name, string mincost, string maxcost)
        {
            decimal min, max;

            if (!decimal.TryParse(mincost, out min) || !decimal.TryParse(maxcost, out max))
                return PartialView("_Table", new List<DefectDTO>());

            if (min > max)
                return PartialView("_Table", new List<DefectDTO>());

            List<DefectDTO> model = db.Defects.GetAll().Select(item => item.ToDefectDTO()).ToList();
            
            model = model.Where(x => x.Name.ToString().StartsWith(name)).ToList();
            model = model.Where(x => x.Cost >= min).ToList();
            model = model.Where(x => x.Cost <= max).ToList();

            return PartialView("_Table", model);
        }

        // GET: Defect/Details/5
        public ActionResult Details(int id)
        {
            var model = db.Defects.Get(id);

            if (model == null)
                return HttpNotFound();

            return View("Details", model.ToDefectDTO());
        }

        // GET: Defect/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: Defect/Create
        [HttpPost]
        public ActionResult Create(DefectDTO model, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var modelDTO = model.ToDefect();
                db.Defects.Create(modelDTO);
                db.Save();
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        // GET: Defect/Edit/5
        public ActionResult Edit(int id)
        {
            var model = db.Defects.Get(id);

            if (model == null)
                return HttpNotFound();

            return View("Edit", model.ToDefectDTO());
        }

        // POST: Defect/Edit/5
        [HttpPost]
        public ActionResult Edit(DefectDTO model, FormCollection collection)
        {
            var modelToUpdate = db.Defects.Get(model.ID);

            if (modelToUpdate == null)
                return HttpNotFound();

            if (ModelState.IsValid)
            {
                modelToUpdate.Name = model.Name;
                modelToUpdate.Cost = model.Cost;
                db.Save();

                return RedirectToAction("Index");
            }

            return View("Edit", model);
        }

        // GET: Defect/Delete/5
        public ActionResult Delete(int id)
        {
            var model = db.Defects.Get(id);

            if (model == null)
                HttpNotFound();

            return View("Delete", model.ToDefectDTO());
        }

        // POST: Defect/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var model = db.Defects.Get(id);

            if (model == null)
                HttpNotFound();

            db.Defects.Delete(id);
            db.Save();
            return RedirectToAction("Index");
        }
    }
}

07BDCourseWork/07BDCourseWork/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using MvcSiteMapProvider.Web.Html
@using _07BDCourseWork.Resources
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/MainCss");
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
</head>
<body class="index">


    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    Menu
                </button>
                @Html.ActionLink("Reports", "Index", "Report", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Workshops", "Index", "Workshop", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Cars", "Index", "Car", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Brigades", "Index", "Brigade", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Defects", "Index", "Defect", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Spare Parts", "Index", "SparePart", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Employees", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Repairs", "Index", "CarRepair", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                </ul>
            </div>
            <ol class="breadcrumb">
                @Html.MvcSiteMap().SiteMapPath()
            </ol>
        </div>
    </nav>

    @RenderSection("banner", false)

    <div id="mainBody" class="container body-content">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p>&copy; @DateTime.Now.Year - Gyrdasov Vladimir</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/Scripts/MainScripts")

</body>

07BDCourseWork/07BDCourseWork/Views/Shared/_PartialSearchBar.cshtml
@using (Ajax.BeginForm("Search", new AjaxOptions {UpdateTargetId = "ajax-table"}))
{
    <div class="row search-bar">
        <div class="col-md-11">
            <div id="imaginary_container">
                <div class="input-group stylish-input-group">
                    <input type="text" class="form-control" placeholder="Search by name" name="name">
                    <span class="input-group-addon">
                    </span>
                </div>
            </div>
        </div>
        <div class="col-md-1">
            <button type="submit" style="height: 33px;" class="btn btn-success">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </div>
    </div>
}

@* Need search in controller and id "search-result in view" *@